# Generated by Django 4.2.4 on 2023-09-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='experience_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
